// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9bNTHn3n4bj-io35qqCHMptR1SA5wDs',
    appId: '1:816695239528:web:9e9692222c7cfe99c2acdd',
    messagingSenderId: '816695239528',
    projectId: 'flutterfirebaseapp-2aa15',
    authDomain: 'flutterfirebaseapp-2aa15.firebaseapp.com',
    storageBucket: 'flutterfirebaseapp-2aa15.firebasestorage.app',
    measurementId: 'G-YH094R3CFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4OcDCEl6sGrMOkvG_BUCloI7LJ5XHq4M',
    appId: '1:816695239528:android:0488a445167f2048c2acdd',
    messagingSenderId: '816695239528',
    projectId: 'flutterfirebaseapp-2aa15',
    storageBucket: 'flutterfirebaseapp-2aa15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFDQTWz6K0dn4oOQDfpYIji17e7rlvkF8',
    appId: '1:816695239528:ios:b6fcec7bfb640b68c2acdd',
    messagingSenderId: '816695239528',
    projectId: 'flutterfirebaseapp-2aa15',
    storageBucket: 'flutterfirebaseapp-2aa15.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
